<?php 
 array_push(
    $apple->row,
    'information_user_id',
    'information_user_id_sha1',
    'information_user_ip', 
    'information_user_login',
    'information_user_name_1',
    'information_user_name_2', 
    'information_user_name_3',
    'information_user_name_4',
    'information_user_adresse_1', 
    'information_user_adresse_2',
    'information_user_adresse_3',
    'information_user_adresse_4', 
    'information_user_password',
    'information_user_img',
    'information_user_born', 
    'information_user_number_1',
    'information_user_number_2',
    'information_user_number_3', 
    'information_user_number_4',
    'information_user_activate',
    'information_user_reg_date' 
    );
    ?>